filters:
  - label: ':bug: fix'
    regexs:
      - \bFix\b
      - \bfix\b

  - label: ':sparkles: FEAT'
    regexs:
      - \bFeat\b
      - \bfeat\b
      - \bFeature\b
      - \bfeature\b

  - label: ':memo: DOCS'
    regexs:
      - \bDocs\b
      - \bdocs\b
      - \bREADME\b

  - label: ':hammer_and_wrench: CHORE'
    regexs:
      - \bChore\b
      - \bchore\b

  - label: ':lipstick: DESIGN'
    regexs:
      - \bDesign\b
      - \bdesign\b

  - label: ':art: STYLE'
    regexs:
      - \bStyle\b
      - \bstyle\b

  - label: ':mailbox_with_mail: API'
    regexs:
      - \bAPI\b
      - \bapi\b

  - label: ':recycle: REFACTOR'
    regexs:
      - \bRefactor\b
      - \brefactor\b

  - label: ':wrench: INIT'
    regexs:
      - \bINIT\b
      - \bInit\b
      - \binit\b

  - label: ':ambulance: !HOTFIX'
    regexs:
      - \bHOTFIX\b
      - \bhotfix\b

  - label: ':bookmark: RELEASE'
    regexs:
      - \bRelease\b
      - \brelease\b
