filters:
  - label: ':bug: fix'
    regexs:
      - /\b[Ff]ix\b/
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':sparkles: FEAT'
    regexs:
      - /\b[Ff]eat\b/
      - /\b[Ff]eature\b/
    events: [issues, pull_request]
    targets: [title]

  - label: ':memo: DOCS'
    regexs:
      - /\b[Dd]ocs\b/
      - /\bREADME\b/
    events: [pull_request]
    targets: [title, comment]

  - label: ':hammer_and_wrench: CHORE'
    regexs:
      - /\b[Cc]hore\b/
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':lipstick: DESIGN'
    regexs:
      - /\b[Dd]esign\b/
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':art: STYLE'
    regexs:
      - /\b[Ss]tyle\b/
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':mailbox_with_mail: API'
    regexs:
      - /\bAPI\b/i
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':recycle: REFACTOR'
    regexs:
      - /\b[Rr]efactor\b/
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':wrench: INIT'
    regexs:
      - /\binit\b/i
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':ambulance: !HOTFIX'
    regexs:
      - /\bhotfix\b/i
    events: [issues, pull_request]
    targets: [title, comment]

  - label: ':bookmark: RELEASE'
    regexs:
      - /\brelease\b/i
    events: [issues, pull_request]
    targets: [title, comment]
