name: Auto Project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Link issue/PR to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/4CO4CO/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
