name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
